version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12.3

    steps:
      - checkout

      - run:
          name: Set up Python virtual environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip

      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest discover tests -b

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
